"""Adding card holder, cvv and card number

Revision ID: 1be14278f16f
Revises: 291ae82b2ffc
Create Date: 2023-03-19 10:11:27.397446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be14278f16f'
down_revision = '291ae82b2ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_holder_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cvv', sa.Integer(), nullable=False, max_length='3'))
        batch_op.add_column(sa.Column('card_number', sa.Integer(), nullable=False, max_length='16'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('card_number')
        batch_op.drop_column('cvv')
        batch_op.drop_column('card_holder_name')

    # ### end Alembic commands ###
