"""Adding new migrations for the DB

Revision ID: 3f1615ff68c7
Revises: 
Create Date: 2023-04-19 13:57:37.344503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1615ff68c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=False),
    sa.Column('available_copies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'book_manager', 'admin', name='roletype'), nullable=False),
    sa.Column('shopping_basket', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=100), nullable=False),
    sa.Column('book_author', sa.String(length=100), nullable=False),
    sa.Column('additional_request', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('price_to_pay', sa.Float(), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('processed', 'pending', 'rejected', name='orderstatus'), nullable=False),
    sa.Column('payment_link', sa.String(length=1024), nullable=True),
    sa.Column('payment_session_id', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
