"""Adding new table: orders. Contains all users orders and their statuses.

Revision ID: 417297f9098b
Revises: 1be14278f16f
Create Date: 2023-03-19 16:35:22.269495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417297f9098b'
down_revision = '1be14278f16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('processed', 'pending', 'rejected', name='orderstatus'), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
