"""Removed unneeded columns in the db

Revision ID: c03c7460faab
Revises: 4dabc18c565d
Create Date: 2023-04-19 13:29:54.666899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03c7460faab'
down_revision = '4dabc18c565d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cvv')
        batch_op.drop_column('card_holder_name')
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('card_holder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cvv', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
