"""Database changes for the orders table and the resource setup.

Revision ID: c39aa26ec180
Revises: 417297f9098b
Create Date: 2023-03-19 17:28:59.757001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39aa26ec180'
down_revision = '417297f9098b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('book_author', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('additional_request', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('price_to_pay', sa.Float(), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopping_basket', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('shopping_basket')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('price_to_pay')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('additional_request')
        batch_op.drop_column('book_author')
        batch_op.drop_column('book_title')

    # ### end Alembic commands ###
